const {
  extraNodeModules,
  watchFolders,
} = require('react-native-yarn-workspaces-v2')(__dirname)

module.exports = {
  watchFolders,
  resolver: {
    extraNodeModules,
  },
  // Generated by `react-native`.
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false,
      },
    }),
  },
  // end
}
