version: '3.1'

services:
  redis:
    container_name: rini-redis
    hostname: redis
    image: redis:5.0.10-alpine
    ports:
      - 6379:6379

  redis-commander:
    container_name: rini-redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8082:8081'
